language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t mehmoodzaman/docker-react -f DockerFile.dev .

script:
  - docker run -e CI=true mehmoodzaman/docker-react npm run test -- --coverage